package com.bank.islamic.sadaqahandcharitymanagement;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

/**
 * BIAN Service Domain: Sadaqah And Charity Management
 *
 * Business Area:      Shariah Governance and Compliance
 * Business Domain:    Shariah Governance
 * Functional Pattern: Manage
 * Asset Type:         Charity Pool
 * Control Record:     Charity Pool Management Plan
 *
 * Generated by the islamic-platform service generator (Phase 1 — shallow build).
 * Replace the in-memory store with real persistence and domain logic in Phase 2.
 */
@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    @Bean
    public OpenAPI openApi() {
        return new OpenAPI().info(new Info()
                .title("Sadaqah And Charity Management — BIAN Semantic API")
                .description("Service Domain 'Sadaqah And Charity Management' (Manage pattern) "
                        + "operating on the 'Charity Pool Management Plan' control record.")
                .version("0.1.0"));
    }
}
